security:
    
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home 
            
            
            logout:
                path: app_logout
                target: app_home 

            
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 

    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

 
    access_control:
        # Routes publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS } 

        # Routes sécurisées 
        - { path: ^/post/new, roles: ROLE_USER }
        - { path: ^/feed, roles: ROLE_USER }
        - { path: ^/messages, roles: ROLE_USER }
        - { path: ^/notifications, roles: ROLE_USER }
        - { path: ^/profile/edit, roles: ROLE_USER }
        - { path: ^/like/post, roles: ROLE_USER }
        - { path: ^/follow/user, roles: ROLE_USER }
        - { path: ^/post/.*/comment, roles: ROLE_USER }
        - { path: ^/comment/.*/delete, roles: ROLE_USER }
        - { path: ^/comment/.*/like, roles: ROLE_USER }
        
        # Sécurité API
        - { path: ^/api/posts, methods: [POST], roles: ROLE_USER }
